---
- hosts: localhost
  name: Setup ONTAP
  gather_facts: no
  vars:
    hostname: "192.168.0.101"
    username: "admin"
    state: present
  vars_prompt:
  - name: "password"
    prompt: "Password:"
  tasks:
  - name: Create Aggrs
    na_ontap_aggregate:
      state: "{{ state }}"
      name: "{{ item.name }}"
      nodes: "{{ item.node }}"
      disk_count: 7
      raid_size: 7
      https: true
      validate_certs: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
    with_items:
      - { name: "n1_aggr1", node: "cluster1-01" }
      - { name: "n1_aggr2", node: "cluster1-01" }
      - { name: "n2_aggr1", node: "cluster1-02" }
      - { name: "n2_aggr2", node: "cluster1-02" }