---
##[PLAY] Deploy Trident on Docker hosts
#- hosts: prod
#  name: Play [Deploy Trident on Docker hosts]
#  tasks:
#  - name: Copy config.json file
#    copy:
#      src: config.json
#      dest: /etc/netappdvp/config.json
#      backup: yes
#  - name: Install Trident on host
#    shell: docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:latest

##[PLAY] Configure ONTAP Cluster
- hosts: localhost
  name: Play [Configure ONTAP Cluster]
  vars_files:
  - variables.yml
  tasks:

#   Create a SVM
  - name: Create a SVM (na_ontap_svm)
    na_ontap_svm:
      state: "{{ state }}"
      name: SVM_Trident
      root_volume: "SVM_Trident_root"
      root_volume_aggregate: n2_aggr1
      root_volume_security_style: unix
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Create an Interface
  - name: Create an Interface (na_ontap_interface)
    na_ontap_interface:
      state: "{{ state }}"
      interface_name: "SVM_Trident_mgmt_data_1"
      home_port: e0e
      home_node: cluster1-02
      role: data
      protocols: nfs
      address: 192.168.0.146
      netmask: 255.255.255.0
      vserver: SVM_Trident
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Configure NFS
  - name: Configure NFS (na_ontap_nfs)
    na_ontap_nfs:
      state: "{{ state }}"
      service_state: started
      vserver: SVM_Trident
      nfsv3: enabled
      nfsv4: disabled
      nfsv41: disabled
      tcp: enabled
      udp: enabled
      vstorage_state: disabled
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Setup Default Rules
  - name: Create default Export Policy Rule (na_ontap_export_policy_rule)
    na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: default
      vserver: SVM_Trident
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: none
      super_user_security: none
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Create Policy
  - name: Create Export Policy (na_ontap_export_policy)
    na_ontap_export_policy:
      state: "{{ state }}"
      name: TridentPolicy
      vserver: SVM_Trident
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

#   Setup Rules
  - name: Create Export Policy Rule (na_ontap_export_policy_rule)
    na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: TridentPolicy
      vserver: SVM_Trident
      client_match: "{{ client }}"
      ro_rule: any
      rw_rule: any
      super_user_security: any
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false