---
- hosts: prod
  name: Play [Deploy Trident on Docker hosts]
  tasks:
  - name: Copy config.json file
    copy:
      src: _trident_config_file.json
      dest: /etc/netappdvp/config.json
      backup: yes
  - name: Install Trident on hosts
    shell: docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:latest
    ignore_errors: yes

- hosts: rhel1
  name: Play [Create persistent volume using Trident, httpd web container, and Snapshot on NetApp volume]
  tasks:
  - name: Pull httpd Docker image
    docker_image:
      name: "httpd"
      source: pull
  - name: Create pvol1 Docker persistent volume
    docker_volume:
      driver: "netapp"
      name: "pvol1"
      driver_options:
        size: "3g"
  - name: Create myweb1 Apache container on rhel1 using the pvol1 persistent volume
    docker_container:
      name: myweb1
      image: httpd
      ports:
        - "80:80"
      volumes:
        - "pvol1:/usr/local/apache2/htdocs"
  - name: Custom web server content
    shell: docker cp ~/ansible/lod/htdocs/index.html      myweb1:/usr/local/apache2/htdocs/index.html
  - name: Custom web server content
    shell: docker cp ~/ansible/lod/htdocs/netapp-logo.png myweb1:/usr/local/apache2/htdocs/netapp-logo.png
  - name: Custom web server content
    shell: docker cp ~/ansible/lod/htdocs/docker_logo.png myweb1:/usr/local/apache2/htdocs/docker_logo.png
  - name: Custom web server content
    shell: docker cp ~/ansible/lod/htdocs/trident.png     myweb1:/usr/local/apache2/htdocs/trident.png

  - name: Create the Snapshot backup1 on the NetApp volume
    na_ontap_snapshot:
      snapshot: backup1
      volume: docker_pvol1
      vserver: SVM_NFS
      username: admin
      password: Netapp1!
      hostname: 192.168.0.101
      https: true
      validate_certs: false
