---
- hosts: prod
  name: Play [Deploy Trident on Docker hosts]
  tasks:
  - name: Copy config.json file
    copy:
      src: ~/config.json
      dest: /etc/netappdvp/config.json
      backup: yes
  - name: Install Trident on host
    shell: docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:latest
