---
- hosts: prod
  name: Play [Deploy Trident on Docker hosts rhel1 and rhel2]
  tasks:
  - name: Copy config.json file to both rhel1 and rhel2
    copy:
      src: _trident_config_file.json
      dest: /etc/netappdvp/config.json
      backup: yes
  - name: Install Trident on hosts rhel1 and rhel2
    shell: docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:latest
    ignore_errors: yes

#- hosts: rhel1
#  name: Play [Create Docker Persistent Volume pvol1]
#  tasks:
  - name: Creating pvol1
    docker_volume:
      driver: "netapp"
      name: "pvol1"
      driver_options:
        size: "3g"
    run_once: true
    delegate_to: rhel1

#- hosts: prod
#  name: Play [Create the Apache Container myweb1 on rhel1 and rhel2 using the Persistent Volume pvol1 for its data repository]
#  tasks:
  - name: Create the Apache Container myweb1 on rhel1 and rhel2 using the Persistent Volume pvol1 for its data repository
    docker_container:
      name: myweb1
      image: httpd
      ports:
        - "80:80"
      volumes:
        - "pvol1:/usr/local/apache2/htdocs"

#- hosts: rhel1
#  name: Play [Finalize the Web Server myweb1 and Create a backup of the Web Server Data]
#  tasks:
  - name: Customize the Web Server content
    shell: docker cp ~/ansible/lod/htdocs/ myweb1:/usr/local/apache2/
    run_once: true
    delegate_to: rhel1
    
  - name: Create the Snapshot backup1 on the NetApp volume
    na_ontap_snapshot:
      snapshot: backup1
      volume: docker_pvol1
      vserver: SVM_NFS
      username: admin
      password: Netapp1!
      hostname: 192.168.0.101
      https: true
      validate_certs: false
