---

##[PLAY] Deploy Trident, Install and Customize Apache Container and Create a Snapshot Backup
- hosts: prod
  name: Play [Deploy Trident, Install and Customize Apache Container and Create a Snapshot Backup]

  tasks:

#   Configure Trident
  - name: Copy config.json file to both rhel1 and rhel2
    copy:
      src: _trident_config_file.json
      dest: /etc/netappdvp/config.json
      backup: yes

#   Install Trident
  - name: Install Trident on hosts rhel1 and rhel2
    shell: docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:latest
    ignore_errors: yes

#   Create Persistent Volume
#  - name: Creating Persistent Volume pvol1
#    docker_volume:
#      driver: "netapp"
#      name: "pvol1"
#      driver_options:
#        size: "3g"
#    run_once: true
#    delegate_to: rhel1
  - name: Creating Persistent Volume pvol1 
    shell: docker volume create -d netapp --name pvol1 --opt size=3G 
    ignore_errors: yes
    run_once: true
    delegate_to: rhel1

#   Create Apache Container
  - name: Create the Apache Container myweb1 on rhel1 and rhel2 using the Persistent Volume pvol1 for its data repository
#    docker_container:
#      name: myweb1
#      image: httpd
#      ports:
#        - "80:80"
#      volumes:
#        - "pvol1:/usr/local/apache2/htdocs"
    shell: docker container run --detach --publish 80:80 --name myweb1 --volume pvol1:/usr/local/apache2/htdocs httpd 
    ignore_errors: yes


#   Customize the Web Server
  - name: Customize the Web Server content
    shell: docker cp ~/workspace/htdocs/ myweb1:/usr/local/apache2/
    run_once: true
    delegate_to: rhel1

#   Create a Snapshot backup of the Web Server Content    
  - name: Create the Snapshot backup1 on the NetApp volume
    na_ontap_snapshot:
      snapshot: backup1
      volume: docker_pvol1
      vserver: SVM_NFS
      username: admin
      password: Netapp1!
      hostname: 192.168.0.101
      https: true
      validate_certs: false
    run_once: true
    delegate_to: localhost